arrowParens: 'avoid'
singleQuote: true
bracketSpacing: true
endOfLine: 'lf'
semi: false
tabWidth: 2
trailingComma: 'none'
printWidth: 100
plugins:
  - 'prettier-plugin-tailwindcss'
overrides:
  - files: '*.d.ts'
    options:
      printWidth: 120
