import type { Metadata } from 'next'
import './globals.css'
import { inter } from '@/lib/fonts'
import { Header, ReactQueryClient } from '@/features/core'
import { MedictProvider } from '@/features/medic'
import { ExamsProvider } from '@/features/exams'
import { AppointmentProvider } from '@/features/appointment'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryClient>
          <MedictProvider>
            <AppointmentProvider>
              <ExamsProvider>
                <div className="flex min-h-screen flex-col overflow-hidden">
                  <Header />

                  {children}
                </div>
              </ExamsProvider>
            </AppointmentProvider>
          </MedictProvider>
        </ReactQueryClient>
      </body>
    </html>
  )
}
